const actions = {
  CREATE_DOC: 'CREATE_DOC',
  CREATE_ROLE: 'CREATE_ROLE',
  DELETE_DOC: 'DELETE_DOC',
  EDIT_DOC: 'EDIT_DOC',
  GET_DOC: 'GET_DOC',
  GET_ROLES: 'GET_ROLES',
  GET_USERS: 'GET_USERS',
  USER_DOCS: 'USER_DOCS',
};

export default actions;
