const actions = {
  CREATE_DOC: 'CREATE_DOC',
  CREATE_ROLE: 'CREATE_ROLE',
  DELETE_DOC: 'DELETE_DOC',
  EDIT_DOC: 'EDIT_DOC',
  GET_DOC: 'GET_DOC',
  GET_ROLES: 'GET_ROLES',
  GET_USERS: 'GET_USERS',
  USER_DOCS: 'USER_DOCS',
  FETCH_USERS_START: 'FETCH_USERS_START',
  FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
};

export default actions;
